# Generated by Django 3.0.5 on 2020-07-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_author_authordetail_newbook_publish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newbook',
            options={'ordering': ['id'], 'verbose_name': '新青年书籍', 'verbose_name_plural': '新青年书籍'},
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_delete',
            field=models.BooleanField(default=0),
        ),
    ]
